### ISSUE TITLE
Names missing. (mod incompatibility)

### ISSUE THREAD

**Issue by hiccuphunt** [jpw1991/chebs-necromancy#102]
# Describe the bug

The name above skeletons disappear when you add the Creature Level and loot control mod: https://valheim.thunderstore.io/package/Smoothbrain/CreatureLevelAndLootControl/

# To Reproduce (if applicable)

Add the Creature level and loot control mod V 4.5.4 to your game along side ChebsNecromancy 1.8.8

# Expected behavior (if applicable)

The name should appear, like this:

![image](https://user-images.githubusercontent.com/13718599/220981343-20502235-2f54-4b93-81f2-5f3f5dbaf91b.png)

# Screenshots (if applicable)
![20230222131222_1](https://user-images.githubusercontent.com/34076573/220793689-c7919d71-6db8-4bae-883f-15d7a3b0968e.jpg)

# Desktop

If you can, please complete the following information:

 - OS: [Windows 11]
 - Mod version: 1.8.8
 - Game version

**Comment by jpw1991** [comment]
This is probably a problem regarding Harmony patching on the [Tameables.GetHoverName patch](https://github.com/jpw1991/chebs-necromancy/blob/master/ChebsNecromancy/Patches/TameablePatches.cs#L89). I got in touch with Smoothbrain via discord. Maybe they will help me figure out what's wrong there.

**Comment by jpw1991** [comment]
![image](https://user-images.githubusercontent.com/13718599/221011132-9346ed8d-6f5d-41aa-902d-fc8e3e5134ff.png)

**Comment by jpw1991** [comment]
I got a useful answer from someone else. I'll see what I can do:

![image](https://user-images.githubusercontent.com/13718599/221013746-6d3a30f8-1c6c-4668-b846-f891c65cb888.png)

**Comment by jpw1991** [comment]
I did my best to make the parts of my code more friendly to other mods. So more than that I cannot do for now.
