### ISSUE TITLE
Neckro Gatherers

### ISSUE THREAD

**Issue by myceliated** [jpw1991/chebs-necromancy#103]
# Amount gathered by neckros

Would be great if we could config the neckros to take items they pick up to chests in intervals or something other than when they are completely full

## No problem really, I just cant use the gatherers with the modpack I have currently uses WeightBase so the neckros just pick up things forever because items have no max stack.

Still learning about everything in this mod since I'm barely into Black Forest but its pretty cool so far :)

### Item amount threshold

Ideally, when threshold is reached they would head to a container to store their cargo.

**Comment by jpw1991** [comment]
Hi @myceliated , thanks for your feedback and for opening the issue.

Ok I can do something like:

- every X seconds, Neckro checks its inventory
- if it has stuff in there, it drops it off, regardless of whether it's full or not

That should work

**Comment by CW-Jesse** [comment]
Sorry, didn't see you had already self-assigned @jpw1991.

**Comment by jpw1991** [comment]
@CW-Jesse it's all good, thanks for completing the issue

**Comment by jpw1991** [comment]
@myceliated you can test this [here](https://github.com/jpw1991/chebs-necromancy/pull/148) if you wish. Attention: assumes newest Valhiem version + upgraded BepInEx and Jotunn
