### ISSUE TITLE
Skeletons not mining Silver

### ISSUE THREAD

**Issue by jdalfonso4341** [jpw1991/chebs-necromancy#109]
# Describe the bug

The miner Skeletons are not mining silver

# To Reproduce (if applicable)

Steps to reproduce the bug. For example:
1. Clear silver vein
2. raise ground around the solver, so the skeletons don't go after the stones in the immediate area
3. Summon miner skeletons

# Expected behavior (if applicable)

Mine Silver

# Screenshots (if applicable)

![Screenshot (1210)](https://user-images.githubusercontent.com/125409097/221378309-49b2aeac-f28f-4b65-9627-8d66db0bcfc6.png)

**Comment by suRedLance** [comment]
The same happens for any kind of ore.
Seems like they only look for normal rocks and once there are none in their radius they just freeze in place.
![2023-03-02_13-16](https://user-images.githubusercontent.com/20660635/222427657-0c343e73-c26b-4d1e-9dd9-867ec4bbe764.png)

**Comment by jpw1991** [comment]
Thanks for the feedback. I'll look into this soon

**Comment by CW-Jesse** [comment]
@jpw1991 Any chance this would be fixed using the new `FindClosest`? Woodcutters also not seeing nearby wood. Feels like the neckro problem all over again.

**Comment by jdalfonso4341** [comment]
Dam adorable Neckros. They are too cute not to use.

**Comment by jpw1991** [comment]
Hi @suRedLance & @jdalfonso4341 can you please try adding the following to the config for the miner ores list and seeing if it fixes the problem for silver:

- `silvervein`
- `silvervein_frac`

For copper and other ores, hmm. I am still not sure.

> Any chance this would be fixed using the new FindClosest? Woodcutters also not seeing nearby wood. Feels like the neckro problem all over again.

Yeah it would help I think @CW-Jesse

**Comment by jpw1991** [comment]
Seems like `MineRock_Tin` is the name for the tin. It's hard to find them all

**Comment by jpw1991** [comment]
Ah damn it. `MineRock_Tin` has a different mask

**Comment by jpw1991** [comment]
Alright so they're mining Tin and Obsidian now in my unreleased test version. They are still not mining silver and copper. I'm not sure yet why that is.

@CW-Jesse I also refactored to make use of that FindClosest function

**Comment by suRedLance** [comment]
I have tried out using MineRock_Tin and MineRock_Copper too (using the documentation from Jotunn's) but it doesn't change anything.
I feel like this is more of an AI problem than anything.
Next few days I'll take the `FindClosest` version for a spin, and see if it works.

**Comment by suRedLance** [comment]
Same thing on 2.3.0, just checked.

**Comment by jpw1991** [comment]
> Same thing on 2.3.0, just checked.

Please try [2.3.3](https://github.com/jpw1991/chebs-necromancy/releases/tag/2.3.3)

**Comment by suRedLance** [comment]
> Please try [2.3.3](https://github.com/jpw1991/chebs-necromancy/releases/tag/2.3.3)
Works on Tin now, but they still ignore copper, even when standing on top of a full vein.

**Comment by jpw1991** [comment]
This one really isn't making sense to me. Technical "proof" that it should be able to mine copper:

![image](https://user-images.githubusercontent.com/13718599/227415062-392aac7e-7663-4dd1-b239-6011d5b3c84a.png)

Because it is no different from tin:

![image](https://user-images.githubusercontent.com/13718599/227415829-1d986d6f-8103-4ad2-937a-3fc8d6b3d5a8.png)

I will probably figure it out eventually, but it's a tough cookie...

**Comment by jpw1991** [comment]
![image](https://user-images.githubusercontent.com/13718599/227750641-6dbe7b7a-25a4-4909-a94e-4b9ec8e66426.png)

Success! I got it! Just gotta polish it up some,t hen I will release
