### ISSUE TITLE
Config not being updated by server players see their local setting only.

### ISSUE THREAD

**Issue by eviltek2099** [jpw1991/chebs-necromancy#111]
Client Recipe: 
SkeletonWandCraftingCosts = Wood:5,Stone:1

and on server it's 
SkeletonWandCraftingCosts = FineWood:15,Stone:10,TrophySkeleton:1

But players only see their local in game.
Discord convo about this issue: on server: https://github.com/Valheim-Modding/Jotunn
and discussion link: https://discord.com/channels/829466376875933756/829469098936631346/1079645137472344126

**Comment by jpw1991** [comment]
fixed in 2.1.0
