### ISSUE TITLE
Orb of Beckoning - 'cancel' option

### ISSUE THREAD

**Issue by Kherae** [jpw1991/chebs-necromancy#115]
Currently, if a ball from orb of beckoning is up there is not really a way to 'cancel' the order to attack, so to speak. this is a little problematic as while the balls are up minions cannot be teleported. I would like for secondary attack on the thing to destroy all of its active projectiles.

**Comment by jpw1991** [comment]
Hi @Kherae , thanks for the feedback and testing.

You can actually cancel already. Pressing F again should recall all minions chasing the orb. So the workflow is:

1. Throw the orb
2. Minions chase it
3. You want them to shop chasing and return? Press F. Any minions following the Orb will follow you again
4. If you want them immediately back to you, press G after they've started following you again.

I documented this functionality in the [wiki](https://github.com/jpw1991/chebs-necromancy/wiki/OrbOfBeckoning).
