### ISSUE TITLE
Neckro Null Object

### ISSUE THREAD

**Issue by jpw1991** [jpw1991/chebs-necromancy#126]
![image](https://user-images.githubusercontent.com/13718599/222829360-f3fae485-4da8-4419-99be-5c66b4a3c396.png)

**Comment by CW-Jesse** [comment]
What commit is this?

**Comment by jpw1991** [comment]
I'm thinking it can only be `_monsterAI`:

```cs
        private Container GetNearestDropOffPoint() {
            // Container closestContainer;
            Container closestContainer = FindClosest<Container>(DropoffPointRadius.Value, pieceMask,
                c => c.GetInventory().GetEmptySlots() > 0);
            if (closestContainer == null) return null;
            
            // move toward that piece
            _monsterAI.SetFollowTarget(closestContainer.gameObject);
            return closestContainer;
        }
        ```

**Comment by CW-Jesse** [comment]
What's the NeckroStatus when this error occurs? Can't recreate the error by removing nearby containers.

**Comment by jpw1991** [comment]
> It's a problem with the FindClosest method. Probably happens when no Containers or something. Thanks for finding this!

Maybe this line? `.Where(t => t.GetComponent<ZNetView>().IsValid()) // TODO: explain`

Perhaps no ZNetView is there

**Comment by jpw1991** [comment]
That seems to fix it for now, so I am going to release that as a hotfix and we can investigate better solutions later. Just gotta stop ppls games crashing etc.
