### ISSUE TITLE
Efficiency improvement for worker minions

### ISSUE THREAD

**Issue by jpw1991** [jpw1991/chebs-necromancy#130]
# Description

Worker minions pretty regularly scan for stuff to cut/mine. But really they needn't scan very often at all: Trees and rocks don't move. 

## Is the feature related to a problem?

Yes. Having a lot of miners/lumberjacks can cause framerate drops.

### Large Scan + Small Scan

I think there should be an infrequent large scan accompanied by more regular smaller scans.

**Large scan:**

1. A large scan is performed that forms a list of trees/rocks in the whole sight radius
2. Until that list is empty, the worker will not perform another large scan again

**Small scan**

Small scans are more frequently done and used to find stuff like logs or rock fragments that have formed as the result of harvesting, but these are always nearby and so the scan can be restricted to just a few meters and only performed after the current target is harvested (eg. tree breaks into logs, perform another small scan, target logs).

#### Workfllow

![workerAI (1)](https://user-images.githubusercontent.com/13718599/222946927-e768953a-1802-4fc6-928c-e6d2c4ea3dba.jpg)

**Comment by CW-Jesse** [comment]
Well, the large list is always empty when it begins, and only ever filled once.

**Comment by CW-Jesse** [comment]
1. Let's see if using the new `FindClosest` for other parts of the AI, such as `LookForCuttableObjects`, speeds it up?
2. What about starting with small radii and increasing it up to the maximum search distance if nothing is found?

**Comment by jpw1991** [comment]
> Well, the large list is always empty when it begins, and only ever filled once.

Whoopsie. Yeah, I had imagined a line there. I promise that is unintentional...

**Comment by CW-Jesse** [comment]
I'm gonna profile the performance of the neckros and woodcutters and report back.

**Comment by CW-Jesse** [comment]
Okay, Neckros are 31% more efficient than the woodcutters due to the new `UndeadMinion.FindClosest`, which I find surprising because I don't think it's optimized. Second surprise: neither is inefficient in the first place. Low FPS **can't** be from their searching AI because they don't search every frame.

**Comment by CW-Jesse** [comment]
Oh, wait, the neckro might be faster just because of the mask.

**Comment by CW-Jesse** [comment]
The only way to make it faster is to start with smaller radii and increase the size as you said. Also, it might help to try `OverlapSphereNonAlloc`:

https://docs.unity3d.com/ScriptReference/Physics.OverlapSphereNonAlloc.html

BUT this might be a case of premature optimization; is there ANY Humanoid you can have a hundred of that wouldn't slow the game down? So much time each frame is spent updating the walking animation on the main thread.

**Comment by CW-Jesse** [comment]
If I made a mod that put the animation updates on another thread, you could probably have hundreds of creatures while still being playable.

**Comment by CW-Jesse** [comment]
![image](https://user-images.githubusercontent.com/2702167/222949131-af558bb9-b2ca-416a-8151-b2f6c548226d.png)

**Comment by CW-Jesse** [comment]
Oh, there's a different problem with the woodcutters that I didn't find until I did the profiling again: The woodcutters were checking for something to cut _every frame_: `nextCheck` is never set to the current time in Awake.

So if you've been running the game for a few hours, woodcutters are going to `LookForCuttableObjects` every frame for `Time.time`/`UpdateDelay` frames. After 3 hours of playing, that's 1800 frames, or 1.5 minutes at 20 FPS.

**Comment by CW-Jesse** [comment]
I don't know if it should _close_ this issue, but this will definitely help.

**Comment by CW-Jesse** [comment]
Oh, it might. Because 1.5 minutes at 20 FPS is _another_ 1800 frames, so it's not catching up. So it would be a permanent performance loss until... all the computers are restarted? Maybe even the server? Yeah. This was a bigger issue than I thought.

**Comment by CW-Jesse** [comment]
With this fixed and the default time of 6 seconds between searches, the profiler looks like this (with 50 woodcutters and 50 neckros each with search radii of 1000):
![image](https://user-images.githubusercontent.com/2702167/222951016-2039a5ad-1280-42a0-948f-b2227cf71727.png)
That's not bad, considering that is way too high of a search radius.

**Comment by jpw1991** [comment]
Great finds. Thank you
