### ISSUE TITLE
Guardian wraith drops bone fragments

### ISSUE THREAD

**Issue by DeadMor0z** [jpw1991/chebs-necromancy#139]
# Describe the bug

Guardian wraith drops bone fragments on despawn/death.
As there were not any used for summoning it, there should not be any when it vanishes.

**Comment by jpw1991** [comment]
Hi, thanks I'll fix it soon

**Comment by jpw1991** [comment]
@DeadMor0z if you can grab the test version [here](https://github.com/jpw1991/chebs-necromancy/releases/tag/2.3.5) and write problems you find either here or on the merge request, that would be great.
