### ISSUE TITLE
combine crates to reduce pollution

### ISSUE THREAD

**Issue by jpw1991** [jpw1991/chebs-necromancy#142]
# Description

When minions die, they can drop a crate that floats in water. This stops their items from sinking which is good. But it'd be nice if rather than making a new crate for every minion that if a crate already exists, fill it up with items.

## Is the feature related to a problem?

Yes. Dozens of crates with 2 deerhide is not as nice as a few crates or one crate.

## Solutions

- When creature dies, do a quick scan for a crate nearby
- No crate found? Behave as normal
- Crate found? Attempt to add items to it. If successfully transferred, great. If transfer is only partial or there's a remainder, create a new crate

## Considerations

- Conflicts
  - If 10 minions die at the same time, it's not good if all of these are trying to access the same crate.
  - To resolve that, I think minions should add their stuff to a queue which then gets processed sequentially

**Comment by Kherae** [comment]
if possible, some filtering based on owner (for multiplayer)
