### ISSUE TITLE
Necros try to pickup items in Item Drawers Mod

### ISSUE THREAD

**Issue by Dusk-Mage** [jpw1991/chebs-necromancy#147]
# Describe the bug

When you have Item Drawers installed Necros will try to take items from the item drawers causing them to constantly pace and announce which item they are trying to get

# To Reproduce (if applicable)

Steps to reproduce the bug. For example:
1. Install Item Drawers (https://valheim.thunderstore.io/package/makail/ItemDrawers/)
2. Put item like Bone Fragments in the Item Drawer
3. Do a RemoveDrops admin command (To be safe)
4. Place Necro Totem and summon Necro
5. Watch Necro try and get Bone Fragments

# Expected behavior (if applicable)

The Necro wont try and get the bone fragments from the drawer

# Screenshots (if applicable)

![20230314112757_1](https://user-images.githubusercontent.com/19332882/225052009-5de90a33-bc7f-49ca-bbb6-897e417a7f2e.jpg)

# Desktop

If you can, please complete the following information:
 - OS: Windows
 - Mod version: 2.3.2

**Comment by jpw1991** [comment]
Hi @Dusk-Mage , thanks for reporting this. I'll see what I can do

**Comment by jpw1991** [comment]
The mod seems closed source and the author has 0 contact information. I've [asked](https://discord.com/channels/807356896637354004/816011331903684628/1085250311536521266) on the discord to see if anyone knows who they are... maybe something will come of it.

**Comment by jpw1991** [comment]
Sorry @Dusk-Mage I reached out on both discord and the nexus. No responses. So I can't progress with this one. If that ever changes, I'll let you know.
