### ISSUE TITLE
summoned draugr have head collision

### ISSUE THREAD

**Issue by subsanity** [jpw1991/chebs-necromancy#163]
# Describe the bug
Summoned draugr minions have collision with their heads/helmets as if they are solid objects; you can jump on them and they collide with the camera.  Confirmed that this happens with no other mods and a fresh world.

# To Reproduce (if applicable)
1. Spawn a draugr, either melee or an archer
2. Swing your camera around to try and put the draugr between your character and your viewpoint, or try to jump on top of the minion

# Expected behavior (if applicable)
Undead minions are not supposed to have player collision and are definitely not supposed to collide with the camera

# Screenshots (if applicable)
N/A

# Desktop
 - OS: Windows 10
 - Mod version:  2.4.4
 - Game version:  0.214.2

**Comment by jpw1991** [comment]
Thank you, I will look into this

**Comment by jpw1991** [comment]
fun fact: you're not colliding with their head, nor their helmet. You're colliding with their eyeballs lmao. Fixed in next version
