### ISSUE TITLE
draugr minions with "needle" melee weapon do not attack

### ISSUE THREAD

**Issue by subsanity** [jpw1991/chebs-necromancy#165]
# Describe the bug
Draugr minions with the "needle" weapon do not attack.  They will aggro on nearby creatures, close in to melee range, and just stand there.    Skeleton minions do not have this issue.  Confirmed in a fresh world with no other mods.

# To Reproduce (if applicable)
Spawn any draugr minion with the requisite needles in your inventory and approach an enemy creature.

# Expected behavior (if applicable)
The draugr minions should attack when in melee range.

# Screenshots (if applicable)
N/A

# Desktop
 - OS:  Windows 10
 - Mod version:  2.4.4
 - Game version:  0.214.2

**Comment by jpw1991** [comment]
Thank you. This is because the weapon uses an animation that skeletons have, but draugr do not have. I will need to create a different version for them. It will be fixed in the next version
