### ISSUE TITLE
DropOnDeath inconsistencies

### ISSUE THREAD

**Issue by subsanity** [jpw1991/chebs-necromancy#166]
# Describe the bug
With DropOnDeath set to "Just Resources", the cargo crate dropped on draugr minion death will contain any resource used to armor them and three bones.  With DropOnDeath set to "Everything", the cargo crate will contain three bones, plus the amount set with DraugrBoneFragmentsRequired, and any resource used to armor them.  The draugr minion will also drop 1x resource when their body poofs, returning more total resource than was spent to create them.

The skeleton minions do not leave behind extra bones in their crates and they do not return more resource than was spent.  Both minion types can randomly drop bones on death like any creature.

# To Reproduce (if applicable)
With PackDroppedItemsIntoCargoCrate enabled and DropOnDeath set to Just Resources, summon a draugr minion, dismiss it with your wand, and note the 3x bones in the crate.  Set DropOnDeath to Everything, summon & dismiss, and note the 3+DraugrBoneFragmentsRequired bones in the crate.  If armoring the draugr with a resource like iron, note also the iron in the crate and iron yielded by the corpse.

# Expected behavior (if applicable)
I would expect the returned resources to equal as much as was spent.

# Screenshots (if applicable)
N/A

# Desktop
 - OS: Windows 10
 - Mod version:  2.5.8
 - Game version:  0.214.2

**Comment by jpw1991** [comment]
Hello @subsanity , thanks for opening the issue.

I'll look into this soon.

**Comment by jpw1991** [comment]
I did some overhauling a week or two back with regard to this issue. It works better now, but is not totally fixed. I'll look into it again soon. Idk why it's such a tough cookie

**Comment by jpw1991** [comment]
I think it's all working now in 3.3.3. You can test it if you want to: https://github.com/jpw1991/chebs-necromancy/pull/215
