### ISSUE TITLE
Defenders spawn when only tamed creatures are nearby

### ISSUE THREAD

**Issue by John23Anthony** [jpw1991/chebs-necromancy#170]
# Describe the bug

The guardian wraith, bats and ghosts from the relevant pylons continue to spawn when only tamed creatures are nearby.

# To Reproduce (if applicable)

1.  Go somewhere where there are no bad guys.
2.  Spawn in a boar, and tame it (I did both of these via console but it happens even when the tamed creature is tamed naturally)
3.  Equip the Spectral Shroud, or place one of the defender pylons.
5.  Watch the defenders spawn and find life incredibly boaring because there is nothing but a friendly boar in the vicinity.

# Expected behavior (if applicable)

I asked in Discord if it was intended behaviour, and it was suggested that it was not. The "Spirits" are only meant to spawn when untamed baddies or those not part of the player faction are nearby. Or, so I've been told.

# Screenshots (if applicable)

![20230330220004_1](https://user-images.githubusercontent.com/15304135/228963645-2875d9c0-2288-4ae4-a45c-6503ad11520d.jpg)

![20230330220017_1](https://user-images.githubusercontent.com/15304135/228963650-e4ede0be-7a8e-4fb1-80a9-524c827ae436.jpg)

Notice there are no enemies nearby (they've all been killed by the defenders), yet they still hang around and continue to spawn. The only other entity, other than my character, in the area is a tamed boar.

# Desktop

If you can, please complete the following information:

 - OS: Garuda Linux Gnome Edition
 - Mod version: 2.5.11
 - Game version: 214.3
 - BepInEx 5.4.21
 - Jotunn 2.11.2

Notes:
I have tested with only ChebsNecromancy (plus dependencies) installed on both an existing server/character, and have tested it with a fresh character and world, both on a local save and a dedicated server. The "bug" is consistent in all cases.

**Comment by jpw1991** [comment]
> Watch the defenders spawn and find life incredibly boaring because there is nothing but a friendly boar in the vicinity.

Haha! I see what you did there!

Thanks for the detailed bug report. It's kinda related to a much older issue [here](https://github.com/jpw1991/chebs-necromancy/issues/5). Much of what was said back then applies here too.

**Comment by John23Anthony** [comment]
You're most welcome. I just couldn't resist a boaring pun. I had a look at the older issue, and yes there seems to be some overlap there. It's nothing critical, as you have said, so no need to address it unless you feel the need to. I do look forward to an update, however. It can get annoying working around the pig pen, but i'm working around that by unequipping the Shroud.

**Comment by jpw1991** [comment]
Please check here if you want to test the fix https://github.com/jpw1991/chebs-necromancy/pull/175
