### ISSUE TITLE
lumberjack and miner just stand still

### ISSUE THREAD

**Issue by POESSTOMPER** [jpw1991/chebs-necromancy#185]
# Describe the bug

lumberjack and miner just stand still and dont listen to commands they just run  at enemies
# To Reproduce (if applicable)

Steps to reproduce the bug. For example:
1. Interact with skeleton using E
2. Skeleton blows up
3. See error

# Expected behavior (if applicable)

A clear and concise description of what you expected to happen. For example: Skeleton should not blow up.

# Screenshots (if applicable)
![20230410224851_1](https://user-images.githubusercontent.com/130406234/230996860-0d2fd94e-e8d8-4a99-b1ed-dfff61a69920.jpg)

# Desktop

If you can, please complete the following information:

 - Windows
- 3.0.1
 - 0.214.300

**Comment by jpw1991** [comment]
Hi, thanks for reporting this. I think I got a fix for it already. New release coming soon.

**Comment by POESSTOMPER** [comment]
Thanks, They are working fine now but they just one shot all rocks I dont know if its supposed to be like this.
![20230411094838_1](https://user-images.githubusercontent.com/130406234/231092847-85c1e47f-6ce4-4127-be61-9a1ad9833e99.jpg)
