### ISSUE TITLE
Woodcutters unable to cut birch and above

### ISSUE THREAD

**Issue by Axeelf** [jpw1991/chebs-necromancy#189]
# Describe the bug

Skeleton woodcutters are unable to cut trees, stumps and logs for birch and above.
I didn't have this issue with version 3.0.1(last time i used woodcutters recently).
Disabled creature level and loot control, changed necromancy skill to get 0 and 2 star woodcutters(i was on 39, had 1 star), still the same results. Looking at my mod list, i don't have any other mods that change either wood hardness, or tame stats/behaviour.

Config setting for tool quality doesn't seem to impact anything(was on 4-black metal before, no change with setting it to other)

To Reproduce (if applicable)

1. spawn woodcutter near birch or above hardness destroyable
2. observe skeletons attempt to cut wood

# Expected behavior (if applicable)

Workers should be able to cut any tree, i did farm oak with them, can remember something about yggdrasil wood too, so technically they should be able to cut everything.
# Screenshots (if applicable)

![wood too hard](https://user-images.githubusercontent.com/48357923/231256247-80e54ed7-d716-4c01-b6a9-1619d7246171.png)

![wood too hard 2](https://user-images.githubusercontent.com/48357923/231259066-cfd04571-50eb-489b-9ee3-c909fc18b10c.jpg)

# Desktop

 - OS: win 10
 - Mod version: 3.0.3
 - Game version 0.214.300

**Comment by jpw1991** [comment]
Hello, this should be fixed in 3.0.4. If it isn't, please reopen the isuse. Thanks again :)
