### ISSUE TITLE
Neckrogatherer's can't find containers

### ISSUE THREAD

**Issue by Pete100x** [jpw1991/chebs-necromancy#203]
# Describe the bug
Necrogatherers can't find containers, I get an console error stating the issue. Log and cfg attached, .cfg renamed to .txt  . Removed Steam identifiers from log. 

# To Reproduce (if applicable)
I add 1 necktail in to the pylon, neck starts to gather but moment later I get console error and neck stays in one place and doesn't empty it's cargo to nearest chest. I tried whitelisting blackmetalchest with no difference. 
I have 100+ mods installed and hard to pinpoint where the issue may be. I have ItemStacks by mtnewton modifying stacksize in chests 10 times more. So 50 is 500 etc. Just a thought that it might be the case. Can't change it back to normal as I would lose tons of materials. 

# Expected behavior (if applicable)

Thought they would fill chests

# Screenshots (if applicable)

[If applicable, add screenshots to help explain your problem.]

(https://ibb.co/GHF3JTf)

# Desktop

If you can, please complete the following information:
Win10
mod version 3.2.0
latest game version
 - OS: [e.g. Linux, Windows, OS X]
 - Mod version
 - Game version
[com.chebgonaz.ChebsNecromancy.txt](https://github.com/jpw1991/chebs-necromancy/files/11415251/com.chebgonaz.ChebsNecromancy.txt)
[LogOutput.log](https://github.com/jpw1991/chebs-necromancy/files/11415252/LogOutput.log)

**Comment by jpw1991** [comment]
Hi Pete,

## Log

Examining your log (trimming out the big error stack trace stuff), the source of your problems is this:

> [Info   :ChebsNecromancy] Read updated config values
[Error  :ChebsNecromancy] Please check your config entries for spelling and format!
[Info   :ChebsNecromancy] Read updated config values
[Error  :ChebsNecromancy] There was an issue loading your com.chebgonaz.ChebsNecromancy.cfg: 
[Error  :ChebsNecromancy] Please check your config entries for spelling and format!

So looks like your config file is somehow problematic.

## Config

Let's take a look:

```
## The containers that are sorted. Please use a comma-delimited list of prefab names. [Synced with Server]
# Setting type: String
# Default value: piece_chest_wood,piece_chest_blackmetal
ContainerWhitelist = piece_chest_wood
```

You accidently put the `piece_chest_blackmetal` on the commented line. It should go on the value eg. `ContainerWhitelist = piece_chest_wood,piece_chest_blackmetal`

Aside of that though: **there is nothing wrong with this config file** and it cannot be the cause of the errors in the log. Is there another one coming from the server?

# Conclusion

I think a config from the server has problems and is causing everything to go wrong

---

# Other problems unrelated to Cheb's Necromancy

## Error in ProperPortals

```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ProperPortals.ProperPortalsPlugin.UpdateActivationRange (TeleportWorld portal) (at <83a0eb5567964047a1828ab6bd5eb7f1>:0)
ProperPortals.ProperPortalsPlugin+TeleportWorld_Patches.Awake_Postfix (TeleportWorld __instance) (at <83a0eb5567964047a1828ab6bd5eb7f1>:0)
(wrapper dynamic-method) TeleportWorld.DMD<TeleportWorld::Awake>(TeleportWorld)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ZNetScene:CreateObject(ZDO)
ZNetScene:CreateObjectsSorted(List`1, Int32, Int32&)
ZNetScene:CreateObjects(List`1, List`1)
ZNetScene:DMD<ZNetScene::CreateDestroyObjects>(ZNetScene)
ZNetScene:Update()
```

**Comment by jpw1991** [comment]
No worries @Pete100x . I'm glad you solved the issue. Have fun & feel free to reach out again if you run into problems.
