### ISSUE TITLE
Treasure Pylon not working

### ISSUE THREAD

**Issue by Dracken91** [jpw1991/chebs-necromancy#222]
# Description

Treasure Pylon is not sorting items. Github would not allow me to send a .cfg file so I copied it and changed the extension to .txt.

## Attachments Checklist
[LogOutput.log](https://github.com/jpw1991/chebs-necromancy/files/11808142/LogOutput.log)
[com.chebgonaz.ChebsNecromancy - Copy.txt](https://github.com/jpw1991/chebs-necromancy/files/11808152/com.chebgonaz.ChebsNecromancy.-.Copy.txt)

**Comment by jpw1991** [comment]
Good job renaming the config file and setting up the issue, thanks.

This is a bug I can fix in the next version.

---

Other problems in the log:

**Teleport Everything** is not working:

```
[Error  : Unity Log] MissingMethodException: long ZDOMan.GetMyID()
Stack trace:
TeleportEverything.Plugin+TeleportToPatch.Postfix (System.Boolean __result, Player __instance, UnityEngine.Vector3 pos, UnityEngine.Quaternion rot, System.Boolean distantTeleport) (at <f9cba39a82cc4b4893f9e0a070155dbb>:0)
(wrapper dynamic-method) Player.DMD<Player::TeleportTo>(Player,UnityEngine.Vector3,UnityEngine.Quaternion,bool)
(wrapper dynamic-method) Teleport.DMD<Teleport::Interact>(Teleport,Humanoid,bool,bool)
Teleport.OnTriggerEnter (UnityEngine.Collider collider) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
```
