### ISSUE TITLE
Add Healing Spell to Skeleton Mages

### ISSUE THREAD

**Issue by jpw1991** [jpw1991/chebs-necromancy#227]
# Add Healing Spell to Skeleton Mages

Request by Discord user `Hong Kong Phooey`:

> Skeleton Mage Medics: Give them the ability to heal themselves, you and surrounding friendlies, in addition to flinging fireballs. This would make them not simply nice to have, but essential for any proper undead horde.

**Comment by Xiezeru** [comment]
-the healer should be using some kind of dark energy to heal (simply a cosmetic thing).
-the player can only be healed after the become a lich (more lore frendly, undead can not be healed the same way as the living)
