### ISSUE TITLE
Negotiation Skill

### ISSUE THREAD

**Issue by jdalfonso4341** [jpw1991/chebs-necromancy#230]
# Description

This request is for Cheb's mercenaries. A skill that improves mercenary quality and lowers cost as you level it.

## Is the feature related to a problem?

Yes when using the Mercenary mod in conjunction with Cheb;s necromancy, the mod becomes redundant as skeletons cost less. Adding a skill to the mod, gives players a reason to want to use hire mercenaries.

**Comment by jpw1991** [comment]
Closing just because I moved it over to the mercenaries repository. Thanks Juan it's a good idea
