### ISSUE TITLE
Hover error for Skeleton Wand

### ISSUE THREAD

**Issue by Onins** [jpw1991/chebs-necromancy#251]
There's an error when using this mod with Recipe Description Expansion by Azumatt when we hover the Skeleton Wand item. The error will spam if we hover only the skeleton wand both inventory and crafting. The orb of beckoning is not affected on this, only the wand

[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
RecipeDescriptionExpansion.Functions+<>c.<FormatSetName>b__2_0 (System.String i) (at <ff3f612b1280421892345383685aabca>:0)
System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].MoveNext () (at <a790f10e63dd4341b206460141e07e75>:0)
System.String.Join (System.String separator, System.Collections.Generic.IEnumerable`1[T] values) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
RecipeDescriptionExpansion.Functions.FormatSetName (ItemDrop+ItemData item) (at <ff3f612b1280421892345383685aabca>:0)
RecipeDescriptionExpansion.Functions.CustomSetTooltip (ItemDrop+ItemData itemData, ItemDrop+ItemData+SharedData sharedData) (at <ff3f612b1280421892345383685aabca>:0)
RecipeDescriptionExpansion.ItemDropItemDataPatch.Postfix (ItemDrop+ItemData item, System.Int32 qualityLevel, System.Boolean crafting, System.String& __result) (at <ff3f612b1280421892345383685aabca>:0)
(wrapper dynamic-method) ItemDrop+ItemData.DMD<ItemDrop+ItemData::GetTooltip>(ItemDrop/ItemData,int,bool,single)
ItemDrop+ItemData.GetTooltip () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
(wrapper dynamic-method) InventoryGrid.DMD<InventoryGrid::CreateItemTooltip>(InventoryGrid,ItemDrop/ItemData,UITooltip)
(wrapper dynamic-method) InventoryGrid.DMD<InventoryGrid::UpdateGui>(InventoryGrid,Player,ItemDrop/ItemData)
(wrapper dynamic-method) InventoryGrid.DMD<InventoryGrid::UpdateInventory>(InventoryGrid,Inventory,Player,ItemDrop/ItemData)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::UpdateInventory>(InventoryGui,Player)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::Update>(InventoryGui)

**Comment by jpw1991** [comment]
Hello,

It could be my error if the Skeleton Wand item is somehow problematic or unusually set up. Otherwise the issue likely lies in the `RecipeDescriptionExpansion.Functions.FormatSetName` function of the other mod.

I asked Azumatt so we'll hopefully know soon.

**Comment by Onins** [comment]
Thanks for the response, hopefully Azumatt will be able to fix this.

**Comment by jpw1991** [comment]
@Onins is this still a problem?
