### ISSUE TITLE
The mod is not installed like other mods

### ISSUE THREAD

**Issue by Adamantikus** [jpw1991/chebs-necromancy#252]
[LogOutput.log](https://github.com/jpw1991/chebs-necromancy/files/13834320/LogOutput.log)
https://file.io/rh7q4VxGy3An
https://file.io/xnMBPoBcypy6
I don't know how to make it right, English is not my native language
The files are located in the Steam folders

**Comment by jpw1991** [comment]
`[Error  : Unity Log] MissingMethodException: Method not found: ZInput/ButtonDef.ZInput.AddButton(string,UnityEngine.KeyCode,single,single,bool,bool)`

This suggests that you're using the wrong version of Valheim for the mods you've got installed. Please install the most up to date version of Jotunn & the Valheim version from Steam.

**Comment by Adamantikus** [comment]
Thanks for the help. Steam updates Valheim automatically, but Jotun has released a new version, and it had to be updated. Everything worked. Thanks again.
