### ISSUE TITLE
NeckroGatherers Unkillable

### ISSUE THREAD

**Issue by MacBlackCat** [jpw1991/chebs-necromancy#255]
Simply issue, coop game with a well built base has good enough defense that none of the Neckro's get killed by enemies.

One of the players yoinked multiple stacks of tails into the pylon and chaos ensued.... Yet we cant remove any of them.
None of the wands work on them, `forcedelete 50 ChebGonaz_NeckroGatherer` doesnt work either..

Is there any way to remove them? Or is there a bug going on?

**Comment by jpw1991** [comment]
Hello, can you please try (as an admin) the following command:

`chebgonaz_killallneckros f`

It should work. If not, you can use the game's vanilla `killall` command to kill all NPCs nearby in general. More info on my commands [here](https://github.com/jpw1991/chebs-necromancy/wiki/Console-Commands). Please let me know if that works.

**Comment by MacBlackCat** [comment]
Thanks for quick reply, will test it out and will notify of the results
