### ISSUE TITLE
Refuler Pylon throws error on adding materials

### ISSUE THREAD

**Issue by kelsarhu** [jpw1991/chebs-necromancy#265]
When attempting to fill either smelter or kiln the following error appears in the log 

"[Warning: Unity Log] 05/14/2024 20:30:55: Failed to find rpc method 44531401"

[LogOutput.log](https://github.com/jpw1991/chebs-necromancy/files/15316028/LogOutput.log)

**Comment by jpw1991** [comment]
Fixed in 4.10.1, thank you for your report
