### ISSUE TITLE
Ghosts from Spirit Pylon causing errors

### ISSUE THREAD

**Issue by Visteus** [jpw1991/chebs-necromancy#271]
Attached the logfile as well, but here's the relevant error:
[logfile.txt](https://github.com/user-attachments/files/15888549/logfile.txt)

`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) Humanoid.DMD<Humanoid::SetupVisEquipment>(Humanoid,VisEquipment,bool)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::SetupEquipment>(Humanoid)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::EquipItem>(Humanoid,ItemDrop/ItemData,bool)
Humanoid.GiveDefaultItem (UnityEngine.GameObject prefab) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
Humanoid.GiveDefaultItems () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
Humanoid.Start () (at <67f3c386e04446c49523ecfd5b8921c2>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) Humanoid.DMD<Humanoid::SetupVisEquipment>(Humanoid,VisEquipment,bool)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::SetupEquipment>(Humanoid)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::EquipItem>(Humanoid,ItemDrop/ItemData,bool)
Humanoid.GiveDefaultItem (UnityEngine.GameObject prefab) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
Humanoid.GiveDefaultItems () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
Humanoid.Start () (at <67f3c386e04446c49523ecfd5b8921c2>:0)

[Info   : Unity Log] 06/18/2024 09:55:26: Valid True

[Info   : Unity Log] 06/18/2024 09:55:26: On death False

[Info   : Unity Log] 06/18/2024 09:57:54: Spawn time :2.0216 ms

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) Humanoid.DMD<Humanoid::SetupVisEquipment>(Humanoid,VisEquipment,bool)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::SetupEquipment>(Humanoid)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::EquipItem>(Humanoid,ItemDrop/ItemData,bool)
Humanoid.GiveDefaultItem (UnityEngine.GameObject prefab) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
Humanoid.GiveDefaultItems () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
Humanoid.Start () (at <67f3c386e04446c49523ecfd5b8921c2>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) Humanoid.DMD<Humanoid::SetupVisEquipment>(Humanoid,VisEquipment,bool)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::SetupEquipment>(Humanoid)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::EquipItem>(Humanoid,ItemDrop/ItemData,bool)
Humanoid.EquipBestWeapon (Character targetCreature, StaticTarget targetStatic, Character hurtFriend, Character friend) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
MonsterAI.Start () (at <67f3c386e04446c49523ecfd5b8921c2>:0)`

The "NullReferenceException" appears whenever a Spirit Pylon summons a new ghost. Said ghosts often don't move at all, mostly do not attack, and sometimes even get ignored by hostile mobs.

**Comment by jpw1991** [comment]
Hello, thanks for providing your log file.

I can confirm this is a problem that I can also reproduce. Hopefully it will be fixed with the next update

**Comment by jpw1991** [comment]
Fixed in 5.0.0
