### ISSUE TITLE
rebalance of default requirements and quality

### ISSUE THREAD

**Issue by jpw1991** [jpw1991/chebs-necromancy#39]
# Description

From playing the game with my mod extensively, and in light of new fixes like how armor values actually have a real impact now, I think rebalancing of default requirements is needed.

### Item drop

Minions refund half of their materials (except bones?) on death.

### Quality: no star

- Skeletons
  - bone requirement: ~~three~~ 10
  - mage requirement:  ~~one~~ 5 surtling cores
  - boar/deer hide requirement: 5
  - bronze requirement: ~~one~~ 5
  - iron requirement: ~~one~~ 5
  - black metal requirement: ~~one~~ 5
  - archer requirement: ~~nothing~~ 25 wood arrows
- Draugr
  - bone requirement: ~~three~~ 10
  - meat requirement: ~~one~~ 5
  - archer requirement: ~~nothing~~ 25 wood arrows

### Quality: 1 star

Same as base requirements, but doubled (except bones) and with following exceptions:

- higher necromancy level, as it is now
- archer: 25 bronze arrows

### Quality: 2 star (max)

Same as base requirements, but tripled (except bones) and with following exceptions:

- higher necromancy level, as it is now
- archer: 25 iron arrows
- mage: 1 black core

**Comment by Smokeymaxamus** [comment]
Maybe have them as defaults but still configurable like the wand crafting is.
Which is probably the idea, I just didn't see it written yet.
I love all the config options in your mod =)

**Comment by jpw1991** [comment]
@Smokeymaxamus thank you :) yes it would be configurable like the rest

**Comment by jpw1991** [comment]
Reopened because only the item drop part was completed in #68

**Comment by jpw1991** [comment]
Closing because of replacement issue with more exact requirements: https://github.com/jpw1991/chebs-necromancy/issues/82
