### ISSUE TITLE
figure out why SpiritPylonGhosts are colliding with player

### ISSUE THREAD

**Issue by jpw1991** [jpw1991/chebs-necromancy#46]
# Description

Ghosts from the Spirit Pylon have the `SpiritPylonGhostMinion` component which inherits `UndeadMinion`, which should stop player collision. But somehow, in this particular case, it does not.

**Comment by jpw1991** [comment]
I'll be honest: I have no damn clue why this is happening

**Comment by CW-Jesse** [comment]
I think your prefab has an extra collider on it, and since it's on a child object of a `Character`, `collision.gameObject.GetComponent<Character>()` returns null in `UndeadMinion::OnCollisionEnter`.

**Comment by jpw1991** [comment]
> I think your prefab has an extra collider on it, and since it's on a child object of a `Character`, `collision.gameObject.GetComponent<Character>()` returns null in `UndeadMinion::OnCollisionEnter`.

It's probably this. I'll test removing it tomorrow 
![image](https://user-images.githubusercontent.com/13718599/222668697-0ea2baed-2b8f-4337-90f9-727f5e48b008.png)

Maybe its removal breaks the ghost though. We'll see. I don't know what it's for

**Comment by CW-Jesse** [comment]
Doesn't appear to break it. Did you copy it from a creature that hurts you just by touching you?

I used this mod to find it and test its removal:
https://valheim.thunderstore.io/package/sinai-dev/UnityExplorer/

**Comment by jpw1991** [comment]
It's just a copy of the vanilla ghost with some minor changes to its color. I don't know if removing the attack collider will have any effect. I'll test tomorrow

**Comment by jpw1991** [comment]
Yeah removing that fixes the problem. Thank you
