### ISSUE TITLE
make it possible to create armored minions with no material requirement

### ISSUE THREAD

**Issue by jpw1991** [jpw1991/chebs-necromancy#64]
# Description

> [15 January 2023, 2:26PM](https://forum.nexusmods.com/index.php?showtopic=12361378/#entry120488329)
Hi,is there a way to spawn armored skeletons with no materials requirement? Because, for example, when I want to spawn a skeleton with black iron armor and in config the requirement is set to 0, it spawns a basic skeleton (with no armor). I rly enjoy your mod <3

> [15 January 2023, 9:54PM](https://forum.nexusmods.com/index.php?showtopic=12361378/#entry120501388)
Thanks, I'm really happy that you're having fun.
> 
> Right now you can't because it's hard to differentiate between the intended minion. You see: Shift+B has too many jobs. It can create unarmored, leather, bronze, iron, or black iron. But unless the materials are present in the inventory, it can't know which one you want. Right now by having the material in your inventory, it decides that you want that one.
> 
> I'll need to think up some other/better way of doing this to permit what you want. If you have any ideas about that, I'd love to hear them. But right now the lowest you can go is 1 bar. Sorry about that :(

> [15 January 2023, 10:11PM](https://forum.nexusmods.com/index.php?showtopic=12361378/#entry120501883)
Many thanks for fast reply. Maybe you can add adjustable hotkeys for each armored skeleton? So, for example, shift+b for leather armor skeleton, shift+N for bronze armor one and so on, smth like that. Or maybe to create the feature in config where you can disable to spawn each kind of armored skeleton.

> [17 January 2023, 10:31PM](https://forum.nexusmods.com/index.php?showtopic=12361378/#entry120563911)
How about making Shift+B pull up a menu wheel with the choices to click on?

> [18 January 2023, 12:24AM](https://forum.nexusmods.com/index.php?showtopic=12361378/#entry120566530)
The menu + mousewheel seems like the best idea because there are already a lot of keys. I'll give it some thought and hopefully add something to a future version.

**Comment by Dracbjorn** [comment]
I think the easiest way to do this right now until we get the hotbar implemented is to just add a new wand for each type.

**Comment by Dracbjorn** [comment]
Leather Skeleton Wand, Bronze Skeleton Wand, Iron Skeleton Wand, BlackMetal Skeleton Wand.  Adjust the crafting requirements of each one to require the corresponding material type to craft.  Then leave a configuration option to adjust how much metal is required to summon it while allowing zero to not consume any.

**Comment by jpw1991** [comment]
Thanks for sharing your thoughts on that.

I would like to wait for the hotbar because I don't like the idea of adding lots of temporary wands. Inventory space is already at a premium and most of these wands would be useless a lot of the time.

Maybe instead of having the whole `Shift+B` thing, pressing `Shift` can cycle through the resource spending options?
