### ISSUE TITLE
Improvement to attack command

### ISSUE THREAD

**Issue by GoblinSpore** [jpw1991/chebs-necromancy#70]
1. When attack command is given, instead of following a spawned rock, minions start following the closest enemy around (hoping that they in fact will attack a target they're set to follow);
2. When the minion's follow target dies they start following the next closest enemy within aggro range (if present), so you don't have to individually order to attack each enemy in a group;
3. Whenever minions don't have a target to follow (enemy, player or a waiting point), they default to following their player, so when the enemy group is defeated (or generally in any inexplicable situation), unless you specifically order them to wait, your minions always return to you.

**Comment by jpw1991** [comment]
Good suggestion. This needs some additional consideration on the exact mechanism - be it a rock, or an invisible object, or what

**Comment by jpw1991** [comment]
So, giving this some additional thought, what if:

- No rock is spawned, but the area in which a rock would normally be spawned is searched for nearby enemies. If any are found, minions are told to go to that found enemy
- Steps 2 and 3 of your comment above take place

**Comment by jpw1991** [comment]
New idea: what if you just throw like a magic orb and wherever it lands the minions go there? Should be simple

**Comment by GoblinSpore** [comment]
> New idea: what if you just throw like a magic orb and wherever it lands the minions go there? Should be simple

Yeah, attack-move instead of just attacking, seems great
