### ISSUE TITLE
Ability to increase minion limit based on necromancy skill level

### ISSUE THREAD

**Issue by GoblinSpore** [jpw1991/chebs-necromancy#71]
Add a config value for both skeletons and draugr, something like `MaximumSkeletonIncrementSkill = X`, every X levels of necromancy skill increase the maximum number of that minion by 1.

**Comment by jpw1991** [comment]
It's a nice idea. I'll see if we can get it done for 1.8.0

**Comment by jpw1991** [comment]
@GoblinSpore I'd appreciate it if you can visit the [merge request](https://github.com/jpw1991/chebs-necromancy/pull/117), download the binary, install it, and complete the tests
