### ISSUE TITLE
Skeleton Woodcutters and Neckros can't be dismissed

### ISSUE THREAD

**Issue by jpw1991** [jpw1991/chebs-necromancy#95]
# Description

Skeleton woodcutters can't be dismissed and need to be killable with a butcher's knife or similar. The Neckros face a similar problem, although theirs is more complicated due to them having a Container script on them.

### Adding Tameable Isn't Wanted

The problem here is that Butcher's Knife only kills Tameables but adding Tameable to the woodcutter will mess up the current status-display that a woodcutter shows while it runs about doing its thing:

![image](https://user-images.githubusercontent.com/13718599/220737324-22e22b48-bc81-4e0b-b1a5-369131a823a5.png)

As for the Neckros, adding Tameable to them will completely mess up the Container functionality so definitely can't be done.

### Patching Attack

Patching the `Attack.DoMeleeAttack` to check for the woodcutter/neckro and butcher's knife and somehow handle it here would work, but it's kind of a big pain in the booty to do it in this area. Take a look at the method and you'll see what I mean.

### Ideal Solution

The ideal solution would be that the Butcher's Knife can be used to kill the minion. It's simple, players already understand that it works on other minions, but as far as I can see there is no nice or clean way to make it work. Feel free to investigate yourself if you think it can somehow be done.

#### New Wand Action

Add a new action to the wand called Unsummon that will shoot a projectile from the wand that destroys any creature that:

- Belongs to the player
- Has an `UndeadMinion` component

**Comment by Kherae** [comment]
Modifying the butcher knife is not really an 'ideal' solution for potential compatibility down the line.

The new wand action idea seems decent, though that raises the question of keybindings given how there are already multiple in use. The game's keybinding implementation is awful; we don't get modifier combos, so key space is more limited. Would this be using the default secondary attack keybind? possible idea: secondary attack is in some form a way to select what the primary attack of the wand does: melee attack, banishing bolt...or giving other commands. adding yet more keybindings is not really a good call I would think, better to have smarter use of a few keys

**Comment by jpw1991** [comment]
Yeah the hotkey/keybinding thing is always a prohibitive factor. More crazy ideas:

- A consumable item - eat it, minions explode
- Maybe there's a way to detect when the wand is equipped, then mouseover minions highlights them. Then middle click to destroy (like a repair hammer with structures)

**Comment by Kherae** [comment]
consumable...crazy, but probably bad idea. detecting when an item is equipped should be doable though, though 'middle click' is a bit vague. that's typically the default for secondary attack, so do you mean that? I have it rebound on my end, I use middle click for teleporting minions. honestly not a bad idea though.

**Comment by jpw1991** [comment]
What I mean is the same key/button used to destroy a structure with a repair hammer out. For me that's middle click.

**Comment by jpw1991** [comment]
ok so I found a good solution to this. I've been able to implement that hitting minions with a wand destroys them
