### ISSUE TITLE
Archer Weapon Tiers Tied to Arrows

### ISSUE THREAD

**Issue by jpw1991** [jpw1991/chebs-necromancy#98]
# Description

I want more control/input over archer damage. Like, crappy arrows = crappy archers, great arrows = great archers.

## Solutions

- Depends on https://github.com/jpw1991/chebs-necromancy/issues/82 being completed first
- Set archer damage to be whatever the arrow type is, plus/minus some damage according to necromancy level

**Comment by Kherae** [comment]
I'm surprised you didn't add needle arrows. is it because they're too easy to make? might make a nice resource sink for needles alongside the melee skeletons.

**Comment by jpw1991** [comment]
@Kherae it's because of two reasons:

1. The options there currently are so, so strong. Even a big ball of wooden arrow archers, the weakest ones, will melt tough enemies.
2. When you get black metal, there's not much need to and find iron anymore. Black metal skeletons/draugr are much stronger and black metal is easily obtainable from raiding goblin camps. Having iron as the strongest arrow and bronze as the intermediate option gives some need/usefulness for this otherwise pretty useless lategame metal.

If people really want needle arrows though, it'll be easy when https://github.com/jpw1991/chebs-necromancy/issues/82 is done to just change the resource requirements for iron to be needle arrows instead.

---

Closing because issue completed in 2.1.0
